-- Vzdálenosti z Ústí nad Labem do měst v ČR (po silnici, v km)
-- Přesné vzdálenosti bez zaokrouhlení

INSERT INTO distances (start_city, end_city, distance_km) VALUES
-- Krajská města
('Ústí nad Labem', 'Praha', 93),
('Ústí nad Labem', 'Brno', 282),
('Ústí nad Labem', 'Ostrava', 378),
('Ústí nad Labem', 'Plzeň', 148),
('Ústí nad Labem', 'Liberec', 87),
('Ústí nad Labem', 'Olomouc', 308),
('Ústí nad Labem', 'České Budějovice', 218),
('Ústí nad Labem', 'Hradec Králové', 128),
('Ústí nad Labem', 'Pardubice', 152),
('Ústí nad Labem', 'Zlín', 338),
('Ústí nad Labem', 'Jihlava', 208),
('Ústí nad Labem', 'Karlovy Vary', 84),

-- Ústecký kraj - okresní města a větší obce
('Ústí nad Labem', 'Děčín', 31),
('Ústí nad Labem', 'Teplice', 18),
('Ústí nad Labem', 'Most', 34),
('Ústí nad Labem', 'Chomutov', 48),
('Ústí nad Labem', 'Litoměřice', 24),
('Ústí nad Labem', 'Louny', 43),
('Ústí nad Labem', 'Roudnice nad Labem', 36),
('Ústí nad Labem', 'Lovosice', 21),
('Ústí nad Labem', 'Bílina', 23),
('Ústí nad Labem', 'Litvínov', 38),
('Ústí nad Labem', 'Kadaň', 58),
('Ústí nad Labem', 'Žatec', 53),
('Ústí nad Labem', 'Jirkov', 44),
('Ústí nad Labem', 'Klášterec nad Ohří', 62),
('Ústí nad Labem', 'Krupka', 12),
('Ústí nad Labem', 'Duchcov', 26),
('Ústí nad Labem', 'Osek', 29),
('Ústí nad Labem', 'Podbořany', 63),
('Ústí nad Labem', 'Rumburk', 54),
('Ústí nad Labem', 'Varnsdorf', 62),
('Ústí nad Labem', 'Šluknov', 58),
('Ústí nad Labem', 'Benešov nad Ploučnicí', 38),
('Ústí nad Labem', 'Česká Kamenice', 42),
('Ústí nad Labem', 'Třebenice', 32),
('Ústí nad Labem', 'Štětí', 28),
('Ústí nad Labem', 'Povrly', 8),
('Ústí nad Labem', 'Velké Březno', 6),
('Ústí nad Labem', 'Chabařovice', 7),
('Ústí nad Labem', 'Chlumec', 14),

-- Středočeský kraj
('Ústí nad Labem', 'Kladno', 76),
('Ústí nad Labem', 'Mladá Boleslav', 78),
('Ústí nad Labem', 'Kolín', 114),
('Ústí nad Labem', 'Kutná Hora', 128),
('Ústí nad Labem', 'Mělník', 54),
('Ústí nad Labem', 'Beroun', 98),
('Ústí nad Labem', 'Příbram', 132),
('Ústí nad Labem', 'Benešov', 126),
('Ústí nad Labem', 'Nymburk', 94),
('Ústí nad Labem', 'Rakovník', 78),
('Ústí nad Labem', 'Slaný', 64),
('Ústí nad Labem', 'Kralupy nad Vltavou', 56),
('Ústí nad Labem', 'Neratovice', 62),
('Ústí nad Labem', 'Brandýs nad Labem', 74),
('Ústí nad Labem', 'Poděbrady', 98),
('Ústí nad Labem', 'Říčany', 106),
('Ústí nad Labem', 'Čáslav', 138),
('Ústí nad Labem', 'Lysá nad Labem', 86),
('Ústí nad Labem', 'Český Brod', 102),
('Ústí nad Labem', 'Mnichovo Hradiště', 72),
('Ústí nad Labem', 'Vlašim', 142),
('Ústí nad Labem', 'Sedlčany', 138),
('Ústí nad Labem', 'Dobříš', 118),
('Ústí nad Labem', 'Hořovice', 104),
('Ústí nad Labem', 'Votice', 148),

-- Liberecký kraj
('Ústí nad Labem', 'Jablonec nad Nisou', 94),
('Ústí nad Labem', 'Česká Lípa', 58),
('Ústí nad Labem', 'Semily', 108),
('Ústí nad Labem', 'Turnov', 98),
('Ústí nad Labem', 'Nový Bor', 52),
('Ústí nad Labem', 'Tanvald', 102),
('Ústí nad Labem', 'Železný Brod', 96),
('Ústí nad Labem', 'Jilemnice', 114),
('Ústí nad Labem', 'Rokytnice nad Jizerou', 118),
('Ústí nad Labem', 'Harrachov', 126),
('Ústí nad Labem', 'Frýdlant', 96),
('Ústí nad Labem', 'Hrádek nad Nisou', 92),
('Ústí nad Labem', 'Zákupy', 54),
('Ústí nad Labem', 'Mimoň', 64),
('Ústí nad Labem', 'Doksy', 68),

-- Královéhradecký kraj
('Ústí nad Labem', 'Trutnov', 148),
('Ústí nad Labem', 'Náchod', 162),
('Ústí nad Labem', 'Jičín', 108),
('Ústí nad Labem', 'Rychnov nad Kněžnou', 168),
('Ústí nad Labem', 'Dvůr Králové nad Labem', 134),
('Ústí nad Labem', 'Vrchlabí', 138),
('Ústí nad Labem', 'Jaroměř', 144),
('Ústí nad Labem', 'Nová Paka', 118),
('Ústí nad Labem', 'Hořice', 116),
('Ústí nad Labem', 'Broumov', 178),
('Ústí nad Labem', 'Špindlerův Mlýn', 152),
('Ústí nad Labem', 'Pec pod Sněžkou', 158),
('Ústí nad Labem', 'Dobruška', 168),
('Ústí nad Labem', 'Nové Město nad Metují', 156),
('Ústí nad Labem', 'Police nad Metují', 164),
('Ústí nad Labem', 'Kostelec nad Orlicí', 172),
('Ústí nad Labem', 'Hostinné', 142),
('Ústí nad Labem', 'Chlumec nad Cidlinou', 104),

-- Pardubický kraj
('Ústí nad Labem', 'Chrudim', 162),
('Ústí nad Labem', 'Svitavy', 194),
('Ústí nad Labem', 'Ústí nad Orlicí', 178),
('Ústí nad Labem', 'Litomyšl', 186),
('Ústí nad Labem', 'Vysoké Mýto', 172),
('Ústí nad Labem', 'Přelouč', 138),
('Ústí nad Labem', 'Holice', 156),
('Ústí nad Labem', 'Lanškroun', 192),
('Ústí nad Labem', 'Polička', 202),
('Ústí nad Labem', 'Choceň', 174),
('Ústí nad Labem', 'Moravská Třebová', 212),
('Ústí nad Labem', 'Česká Třebová', 188),
('Ústí nad Labem', 'Letohrad', 184),
('Ústí nad Labem', 'Králíky', 208),
('Ústí nad Labem', 'Žamberk', 186),
('Ústí nad Labem', 'Hlinsko', 182),

-- Karlovarský kraj
('Ústí nad Labem', 'Cheb', 128),
('Ústí nad Labem', 'Sokolov', 104),
('Ústí nad Labem', 'Mariánské Lázně', 114),
('Ústí nad Labem', 'Františkovy Lázně', 132),
('Ústí nad Labem', 'Aš', 152),
('Ústí nad Labem', 'Ostrov', 74),
('Ústí nad Labem', 'Kraslice', 116),
('Ústí nad Labem', 'Chodov', 92),
('Ústí nad Labem', 'Jáchymov', 82),
('Ústí nad Labem', 'Nejdek', 86),
('Ústí nad Labem', 'Horní Slavkov', 96),
('Ústí nad Labem', 'Loket', 88),
('Ústí nad Labem', 'Bečov nad Teplou', 94),
('Ústí nad Labem', 'Toužim', 98),
('Ústí nad Labem', 'Habartov', 108),
('Ústí nad Labem', 'Kynšperk nad Ohří', 102),

-- Plzeňský kraj
('Ústí nad Labem', 'Klatovy', 188),
('Ústí nad Labem', 'Domažlice', 178),
('Ústí nad Labem', 'Tachov', 138),
('Ústí nad Labem', 'Rokycany', 128),
('Ústí nad Labem', 'Sušice', 198),
('Ústí nad Labem', 'Horažďovice', 192),
('Ústí nad Labem', 'Stod', 156),
('Ústí nad Labem', 'Stříbro', 136),
('Ústí nad Labem', 'Planá', 142),
('Ústí nad Labem', 'Nýřany', 148),
('Ústí nad Labem', 'Přeštice', 164),
('Ústí nad Labem', 'Kdyně', 172),
('Ústí nad Labem', 'Blovice', 162),
('Ústí nad Labem', 'Nepomuk', 172),
('Ústí nad Labem', 'Horšovský Týn', 168),
('Ústí nad Labem', 'Kralovice', 118),

-- Jihočeský kraj
('Ústí nad Labem', 'Tábor', 178),
('Ústí nad Labem', 'Písek', 198),
('Ústí nad Labem', 'Strakonice', 208),
('Ústí nad Labem', 'Prachatice', 248),
('Ústí nad Labem', 'Český Krumlov', 258),
('Ústí nad Labem', 'Jindřichův Hradec', 228),
('Ústí nad Labem', 'Třeboň', 232),
('Ústí nad Labem', 'Soběslav', 192),
('Ústí nad Labem', 'Blatná', 196),
('Ústí nad Labem', 'Týn nad Vltavou', 204),
('Ústí nad Labem', 'Milevsko', 188),
('Ústí nad Labem', 'Vimperk', 238),
('Ústí nad Labem', 'Volary', 262),
('Ústí nad Labem', 'Dačice', 242),
('Ústí nad Labem', 'Veselí nad Lužnicí', 214),
('Ústí nad Labem', 'Kaplice', 248),
('Ústí nad Labem', 'Vyšší Brod', 268),
('Ústí nad Labem', 'Nové Hrady', 252),
('Ústí nad Labem', 'Trhové Sviny', 238),
('Ústí nad Labem', 'Lomnice nad Lužnicí', 226),

-- Vysočina
('Ústí nad Labem', 'Havlíčkův Brod', 174),
('Ústí nad Labem', 'Pelhřimov', 188),
('Ústí nad Labem', 'Žďár nad Sázavou', 208),
('Ústí nad Labem', 'Třebíč', 238),
('Ústí nad Labem', 'Humpolec', 172),
('Ústí nad Labem', 'Velké Meziříčí', 224),
('Ústí nad Labem', 'Světlá nad Sázavou', 162),
('Ústí nad Labem', 'Chotěboř', 178),
('Ústí nad Labem', 'Bystřice nad Pernštejnem', 218),
('Ústí nad Labem', 'Telč', 232),
('Ústí nad Labem', 'Moravské Budějovice', 252),
('Ústí nad Labem', 'Nové Město na Moravě', 214),
('Ústí nad Labem', 'Náměšť nad Oslavou', 244),
('Ústí nad Labem', 'Pacov', 182),
('Ústí nad Labem', 'Počátky', 196),
('Ústí nad Labem', 'Ledeč nad Sázavou', 158),
('Ústí nad Labem', 'Golčův Jeníkov', 152),

-- Jihomoravský kraj
('Ústí nad Labem', 'Znojmo', 278),
('Ústí nad Labem', 'Břeclav', 308),
('Ústí nad Labem', 'Hodonín', 318),
('Ústí nad Labem', 'Vyškov', 288),
('Ústí nad Labem', 'Blansko', 264),
('Ústí nad Labem', 'Boskovice', 274),
('Ústí nad Labem', 'Tišnov', 268),
('Ústí nad Labem', 'Kuřim', 272),
('Ústí nad Labem', 'Slavkov u Brna', 292),
('Ústí nad Labem', 'Ivančice', 284),
('Ústí nad Labem', 'Pohořelice', 294),
('Ústí nad Labem', 'Hustopeče', 302),
('Ústí nad Labem', 'Kyjov', 322),
('Ústí nad Labem', 'Veselí nad Moravou', 326),
('Ústí nad Labem', 'Mikulov', 312),
('Ústí nad Labem', 'Valtice', 314),
('Ústí nad Labem', 'Lednice', 312),
('Ústí nad Labem', 'Židlochovice', 288),
('Ústí nad Labem', 'Rosice', 274),
('Ústí nad Labem', 'Letovice', 262),
('Ústí nad Labem', 'Velká nad Veličkou', 334),
('Ústí nad Labem', 'Strážnice', 328),
('Ústí nad Labem', 'Bučovice', 298),
('Ústí nad Labem', 'Oslavany', 278),
('Ústí nad Labem', 'Modřice', 282),

-- Olomoucký kraj
('Ústí nad Labem', 'Prostějov', 294),
('Ústí nad Labem', 'Přerov', 318),
('Ústí nad Labem', 'Šumperk', 278),
('Ústí nad Labem', 'Jeseník', 308),
('Ústí nad Labem', 'Hranice', 332),
('Ústí nad Labem', 'Zábřeh', 268),
('Ústí nad Labem', 'Mohelnice', 262),
('Ústí nad Labem', 'Litovel', 298),
('Ústí nad Labem', 'Šternberk', 302),
('Ústí nad Labem', 'Uničov', 296),
('Ústí nad Labem', 'Kojetín', 314),
('Ústí nad Labem', 'Lipník nad Bečvou', 326),
('Ústí nad Labem', 'Zlaté Hory', 322),
('Ústí nad Labem', 'Javorník', 324),
('Ústí nad Labem', 'Hanušovice', 288),

-- Zlínský kraj
('Ústí nad Labem', 'Kroměříž', 328),
('Ústí nad Labem', 'Uherské Hradiště', 348),
('Ústí nad Labem', 'Vsetín', 368),
('Ústí nad Labem', 'Uherský Brod', 358),
('Ústí nad Labem', 'Valašské Meziříčí', 362),
('Ústí nad Labem', 'Rožnov pod Radhoštěm', 372),
('Ústí nad Labem', 'Holešov', 334),
('Ústí nad Labem', 'Otrokovice', 338),
('Ústí nad Labem', 'Napajedla', 342),
('Ústí nad Labem', 'Staré Město', 352),
('Ústí nad Labem', 'Luhačovice', 358),
('Ústí nad Labem', 'Bystřice pod Hostýnem', 348),
('Ústí nad Labem', 'Vizovice', 356),
('Ústí nad Labem', 'Slavičín', 364),
('Ústí nad Labem', 'Valašské Klobouky', 372),
('Ústí nad Labem', 'Brumov-Bylnice', 378),

-- Moravskoslezský kraj
('Ústí nad Labem', 'Opava', 388),
('Ústí nad Labem', 'Karviná', 398),
('Ústí nad Labem', 'Frýdek-Místek', 392),
('Ústí nad Labem', 'Nový Jičín', 368),
('Ústí nad Labem', 'Bruntál', 348),
('Ústí nad Labem', 'Havířov', 394),
('Ústí nad Labem', 'Třinec', 408),
('Ústí nad Labem', 'Orlová', 396),
('Ústí nad Labem', 'Český Těšín', 404),
('Ústí nad Labem', 'Kopřivnice', 372),
('Ústí nad Labem', 'Bohumín', 392),
('Ústí nad Labem', 'Krnov', 358),
('Ústí nad Labem', 'Hlučín', 386),
('Ústí nad Labem', 'Bílovec', 374),
('Ústí nad Labem', 'Studénka', 376),
('Ústí nad Labem', 'Frenštát pod Radhoštěm', 378),
('Ústí nad Labem', 'Příbor', 374),
('Ústí nad Labem', 'Fulnek', 366),
('Ústí nad Labem', 'Odry', 362),
('Ústí nad Labem', 'Vítkov', 356),
('Ústí nad Labem', 'Rýmařov', 342),
('Ústí nad Labem', 'Jablunkov', 418),
('Ústí nad Labem', 'Frýdlant nad Ostravicí', 386),
('Ústí nad Labem', 'Vratimov', 382),
('Ústí nad Labem', 'Šenov', 388),
('Ústí nad Labem', 'Petřvald', 392),

-- Další významná města Praha a okolí
('Ústí nad Labem', 'Roztoky', 84),
('Ústí nad Labem', 'Černošice', 94),
('Ústí nad Labem', 'Hostivice', 86),
('Ústí nad Labem', 'Rudná', 92),
('Ústí nad Labem', 'Unhošť', 82),
('Ústí nad Labem', 'Klecany', 72),
('Ústí nad Labem', 'Odolena Voda', 68),
('Ústí nad Labem', 'Úvaly', 98),
('Ústí nad Labem', 'Jesenice', 104),
('Ústí nad Labem', 'Průhonice', 102),
('Ústí nad Labem', 'Čelákovice', 82)

ON CONFLICT (start_city, end_city) DO UPDATE SET distance_km = EXCLUDED.distance_km;
